In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({"Id":[101, 102], "mob":[9711387195, 8860571995]})

In [3]:
df['mob'] = df['mob'].apply(str)

In [44]:
def nyChar(s,x):
    #x=input("From which index you want numbers:")
    for v in df["mob"]:
        if len(s)%2==0:
            if x=="f":
                i = int(len(s))-int(len(s))
                #print(i,s[i],s[i+1])
                return s[i]+s[i+1]
            elif x=="m": 
                i = int(len(s)/2)-1
                #print(i,s[i],s[i+1])
                return s[i]+s[i+1]
            elif x=="l": 
                i = int(len(s))
                #print(i,s[i-2],s[i-1])
                return s[i-2]+s[i-1]

In [45]:
 df['mobile_char'] =df["mob"].apply(nyChar, x="f")

In [46]:
df.head()

    Id         mob mobile_char
0  101  9711387195          97
1  102  8860571995          88

In [47]:
df['mobile_char'] =df["mob"].apply(nyChar, x="m")
df.head()

    Id         mob mobile_char
0  101  9711387195          38
1  102  8860571995          57

In [48]:
df['mobile_char'] =df["mob"].apply(nyChar, x="l")
df.head()

    Id         mob mobile_char
0  101  9711387195          95
1  102  8860571995          95